- name: Variables from play level
  hosts: localhost 
  tasks:
    - name: check variables 
      ansible.builtin.debug:
        msg: "Hello, I'm learning {{Course}}, Trainer is {{Trainer}} and Duration is {{Duration}}"
    