- name: conditions
  hosts: localhost 
  tasks: 
    - name: check if roboshop user is exist or not 
      ansible.builtin.command: id roboshop 
      register: USER 
    
    - name: print variable "user" value 
      ansible.builtin.debug:
        msg: "User output is {{USER}}"
      